sudo: required

# Useful for the tests
addons:
  chrome: stable

# Use node
language: node_js
node_js:
  - "8"

# Better for performances; enable cache
cache:
  npm: true
  directories:
    - node_modules

env:
  global:
    - CC_TEST_REPORTER_ID=3ceaa52c102780d7c320a400f835b7704db90d262d9f907590fd1f8324feb598

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install

script:
  - npm run lint
  - npm run test-ci

after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./cc-test-reporter upload-coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Allow me to easily track Travis CI
notifications:
  email:
    recipients:
      - geoffrey.testelin@gmail.com
    on_success: change
    on_failure: always

# Plugins
plugins:
  tslint:
    enabled: false # No need to enable it since it is already check with npm script
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig

# White list of branches to build
branches:
  only:
    - master
    - develop
